[build]
  command = "npm run build"
  publish = "dist"

[environment]
  VITE_APPWRITE_PROJECT_ID = "6661f0e6003287ddd060"
  VITE_APPWRITE_URL = "https://cloud.appwrite.io/v1"
  VITE_APPWRITE_STORAGE_ID = "666958bd0015c13dee5a"
  VITE_APPWRITE_DATABASE_ID = "66695930000e2b145904"
  VITE_APPWRITE_SAVES_COLLECTION_ID = "66695a8300004d1a53a2"
  VITE_APPWRITE_POST_COLLECTION_ID = "66695a1000097340d1a5"
  VITE_APPWRITE_USER_COLLECTION_ID = "66695a5a000f2818509e"